# Generated by Django 4.1.7 on 2023-03-02 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vijay', max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('department', models.CharField(max_length=20)),
                ('officeNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,5}', message='Office number should ')])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'Ward'), ('o', 'Operation Theatre')], default='w', max_length=10)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=50)),
                ('scheduledTime', models.DateTimeField()),
                ('testReport', models.FileField(upload_to='')),
                ('reportGenerationTime', models.DateTimeField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tested', to='mainApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opName', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('operationReport', models.FileField(upload_to='')),
                ('reportGenerationTime', models.DateTimeField()),
                ('doctorID', models.ManyToManyField(related_name='doctors', to='mainApp.doctor')),
                ('opTheatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where', to='mainApp.room', validators=[mainApp.models.Operation._validate_room])),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_operated', to='mainApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('appReport', models.FileField(upload_to='')),
                ('reportGenerationTime', models.DateTimeField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assigned', to='mainApp.doctor')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_booked', to='mainApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admitted', to='mainApp.patient')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admitted', to='mainApp.room')),
            ],
        ),
    ]
